/**********************************************************************
Copyright (c)
Audi Autonomous Driving Cup. All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3.  All advertising materials mentioning features or use of this software must display the following acknowledgement: “This product includes software developed by the Audi AG and its contributors for Audi Autonomous Driving Cup.”
4.  Neither the name of Audi nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY AUDI AG AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL AUDI AG OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


**********************************************************************
* $Author:: spie#$  $Date:: 2017-05-11 08:29:51#$ $Rev:: 63032   $
**********************************************************************/

#ifndef _RPMFILTER_H_
#define _RPMFILTER_H_

#define OID_ADTF_CONVERTER_WHEEL "adtf.sop.converterWheels"
/*! @defgroup ConverterWheels Converter Wheels
*  @{
*
* This filter calculates the speed of the vehicle and some distance measurements. It takes the wheel structs containing the direction and the interrupt counter of both wheels from the Arduino sensor as input values. The wheels have a small disk mounted at the inner side and a Transmissive  Encoder Sensor which detects the slots in the rotating disk. The detected slots are transmitted to a interrupt routine at a Arduino which counts the ticks and sends them periodically to ADTF.
* The speed is calculated by the difference between the increasing tick counter in the incoming media samples and the corresponding time  difference between the media samples. For a correct calculation the wheel circumference has to be set to the correct value in the properties, the default value is 0.34m.
* The output samples are triggered to the wheel right struct, so if no samples are received from that sensor no output samples are generated by this filter.
* If the property Filtering enabled is set to true a first order filtering is applied to smooth the signals. The first order filter constant can also be set in the properties.
*
*  \image html ConverterWheels.PNG "Plugin Converter Wheels"
*
* \b Dependencies \n
* This plugin needs the following libraries:
*
* <b> Filter Properties</b>
* <table>
* <tr><th>Property<th>Description<th>Default
* <tr><td>Filter constant first order<td>Set the filter constant for first order here<td>0.3
* <tr><td>Filtering enabled<td>Enables or disables the low pass filtering of speed result<td>False
* <tr><td>Plausibilize with Direction Indicator<td><td>True
* <tr><td>Use Speed Controller Input Direction<td><td>True
* <tr><td>Use Speed Controller Input Direction - Deadband<td><td>0.1000000015
* <tr><td>Wheel circumference<td>Set the wheel circumference in meter here<td>0.34
* </table>
*
* <b> Output Pins</b>
* <table>
* <tr><th>Pin<th>Description<th>Media Description
* <tr><td>WheelLeft_StructPlaus<td><td>tWheelData
* <tr><td>WheelRight_StructPlaus<td><td>tWheelData
* <tr><td>car_speed<td><td>tSignalValue
* <tr><td>distance_lastSample<td><td>tSignalValue
* <tr><td>distance_overall<td><td>tSignalValue
*</table>
*
* <b> Input Pins</b>
* <table>
* <tr><th>Pin<th>Description<th>Media Description
* <tr><td>SpeedController_Struct<td><td>tSignalValue
* <tr><td>WheelLeft_Struct<td><td>tWheelData
* <tr><td>WheelRight_Struct<td><td>tWheelData
* </table>
*
* <b>Plugin Details</b>
* <table>
* <tr><td>Path<td>src/aadcDemo/datafilter/AADC_ConverterWheels
* <tr><td>Filename<td>aadc_converterWheels.plb
* <tr><td>Version<td>1.0.0
* </table>
*
*/

/*! main class for converter wheels plugin */
class SOP_ConverterWheels : public adtf::cFilter
{

    /*! This macro does all the plugin setup stuff
    * Warning: This macro opens a "protected" scope see UCOM_IMPLEMENT_OBJECT_INFO(...) in object.h
    */
    ADTF_DECLARE_FILTER_VERSION(OID_ADTF_CONVERTER_WHEEL, "SOP Converter Wheels", OBJCAT_DataFilter, "Converter Wheels", 1, 0, 2, "");

    /*! Input Pin for wheel struct*/
    cInputPin      m_oInputWheelLeft;

    /*! Input Pin for wheel struct*/
    cInputPin      m_oInputWheelRight;

    /*! Input Pin for speed controller struct*/
    cInputPin      m_oInputSpeedController;

    /*! output pin for the the speed of the wheels */
    cOutputPin m_oOutputCarSpeed;

    /*! output pin for the the distance of distance since adtf start config */
    cOutputPin m_oOutputDistanceOverall;

    /*! output pin for the distance since the last sample */
    cOutputPin m_oOutputDistanceLastSample;

    /*! filtered wheel left struct */
    cOutputPin m_oOutputWheelStructLeft;

    /*! filtered wheel left struct */
    cOutputPin m_oOutputWheelStructRight;

public:
    /*! constructor for class
    *    \param __info   [in] This is the name of the filter instance.
    */
    SOP_ConverterWheels(const tChar* __info);

    /*! Destructor. */
    virtual ~SOP_ConverterWheels();

protected: // overwrites cFilter

    /*! Implements the default cFilter state machine call. It will be
    *	    called automatically by changing the filters state and needs
    *	    to be overwritten by the special filter.
    *    Please see page_filter_life_cycle for further information on when the state of a filter changes.
    *
    *    \param [in,out] __exception_ptr   An Exception pointer where exceptions will be put when failed.
    *        If not using the cException smart pointer, the interface has to
    *        be released by calling Unref().
    *    \param  [in] eStage The Init function will be called when the filter state changes as follows:\n
    *    \return Standard Result Code.
    */
    tResult Init(tInitStage eStage, ucom::IException** __exception_ptr);

    /*! This Function will be called by all pins the filter is registered to.
    *   \param [in] pSource Pointer to the sending pin's IPin interface.
    *   \param [in] nEventCode Event code. For allowed values see IPinEventSink::tPinEventCode
    *   \param [in] nParam1 Optional integer parameter.
    *   \param [in] nParam2 Optional integer parameter.
    *   \param [in] pMediaSample Address of an IMediaSample interface pointers.
    *   \return   Returns a standard result code.
    *   \warning This function will not implement a thread-safe synchronization between the calls from different sources.
    *   You need to synchronize this call by your own. Have a look to adtf_util::__synchronized , adtf_util::__synchronized_obj .
    */
    tResult OnPinEvent(IPin* pSource, tInt nEventCode, tInt nParam1, tInt nParam2, IMediaSample* pMediaSample);

    /*! This Function is always called when any property has changed. This should be the only place
    *    to read from the properties itself and store their values in a member.
    *    \param [in] strName the name of the property that has changed.
    *    \return   Returns a standard result code.
    */
    tResult PropertyChanged(const tChar* strName);

private:

    /*!
     * Gets the time.
     *
     * \return  The streamtime in milliseconds
     */
    tTimeStamp GetTime();

    /*! calculate the speed from two timestamps
    * \param ui32CurrentTimeStamp the new and current timestamp
    * \param ui32LastTimeStamp the former timestamp
    * \param ui32Ticks the ticks since last sample
    * \return calculated speed in meter /sec
    */
    tFloat32 calculateSpeed(const tUInt32 &ui32CurrentTimeStamp, const tUInt32 &ui32LastTimeStamp, const tUInt32 &ui32Ticks = 1);

    /*! with this function all the samples (distance, overall distance, speed) on the output pins are transmitted
    *    \return   Returns a standard result code.
    */
    tResult TransmitSamples();

    /*! descriptor for speed controller input data */
    cObjectPtr<IMediaTypeDescription> m_pDescriptionSpeedController;
    /*! the id for the f32value of the media description for the speed controller input pin */
    tBufferID m_szIDSpeedControllerF32Value;
    /*! the id for the arduino time stamp of the media description for the speed controller input pin */
    tBufferID m_szIDSpeedControllerTimestamp;
    /*! indicates if bufferIDs were set */
    tBool m_bIDsSpeedControllerSet;

    /*! descriptor for wheel sensor data */
    cObjectPtr<IMediaTypeDescription> m_pDescriptionWheelDataLeft;
    /*! the id for the ui32WheelTach of the media description for input pin of the WheelData data */
    tBufferID m_szIDWheelDataLeftUi32WheelTach;
    /*! the id for the i8WheelDir of the media description for input pin of the WheelData data */
    tBufferID m_szIDWheelDataLeftI8WheelDir;
    /*! the id for the arduino time stamp of the media description for input pin of the WheelData data */
    tBufferID m_szIDWheelDataLeftArduinoTimestamp;
    /*! indicates if bufferIDs were set */
    tBool m_bIDsWheelDataLeftSet;

    /*! descriptor for wheel sensor data */
    cObjectPtr<IMediaTypeDescription> m_pDescriptionWheelDataRight;
    /*! the id for the ui32WheelTach of the media description for input pin of the WheelData data */
    tBufferID m_szIDWheelDataRightUi32WheelTach;
    /*! the id for the i8WheelDir of the media description for input pin of the WheelData data */
    tBufferID m_szIDWheelDataRightI8WheelDir;
    /*! the id for the arduino time stamp of the media description for input pin of the WheelData data */
    tBufferID m_szIDWheelDataRightArduinoTimestamp;
    /*! indicates if bufferIDs were set */
    tBool m_bIDsWheelDataRightSet;

    /*! descriptor for wheel sensor data */
    cObjectPtr<IMediaTypeDescription> m_pDescriptionOutputSpeed;
    /*! the id for the f32value of the media description for the actuator output pins */
    tBufferID m_szIDSpeedF32Value;
    /*! the id for the arduino time stamp of the media description for the actuator output input pins */
    tBufferID m_szIDSpeedArduinoTimestamp;
    /*! indicates if bufferIDs were set */
    tBool m_bIDsSpeedSet;

    /*! descriptor for sample distance data */
    cObjectPtr<IMediaTypeDescription> m_pDescriptionOutputSampleDistance;
    /*! the id for the f32value of the media description for the actuator output pins */
    tBufferID m_szIDSampleDistanceF32Value;
    /*! the id for the arduino time stamp of the media description for the actuator output input pins */
    tBufferID m_szIDSampleDistanceArduinoTimestamp;
    /*! indicates if bufferIDs were set */
    tBool m_bIDsSampleDistanceSet;

    /*! descriptor for sample distance data */
    cObjectPtr<IMediaTypeDescription> m_pDescriptionOutputOverallDistance;
    /*! the id for the f32value of the media description for the actuator output pins */
    tBufferID m_szIDOverallDistanceF32Value;
    /*! the id for the arduino time stamp of the media description for the actuator output input pins */
    tBufferID m_szIDOverallDistanceArduinoTimestamp;
    /*! indicates if bufferIDs were set */
    tBool m_bIDsOverallDistanceSet;

    /*! the timestamp of the last left wheel struct */
    tWheelData m_tLastStructLeft;

    /*! the timestamp of the last right wheel struct */
    tWheelData m_tLastStructRight;

    /*! the timestamp of the last left wheel struct */
    tWheelData m_tBeforeLastStructLeft;

    /*! the timestamp of the last right wheel struct */
    tWheelData m_tBeforeLastStructRight;

    /*! the last received speed controller value */
    tSignalValue m_tLastSpeedControllerValue;

    /*! the last calculated speed of right wheel */
    tFloat32 m_f32LastCalculatedSpeedRight;

    /*! the last calculated speed of left wheel */
    tFloat32 m_f32LastCalculatedSpeedLeft;

    /*! holds the overall distance since starting the adtf config*/
    tFloat32 m_f32OverallDistance;

    /*! the wheel circumference in meter */
    tFloat32 m_f32wheelCircumference;

    /*! the filter constant of first order */
    tFloat32 m_f32FilterConstantfirstOrder;

    /*! critical section for on pin event*/
    cCriticalSection m_oCritSectionReceive;

    /*! enables or filtering enabled */
    tBool m_bEnableFiltering;

    /*! plausibilization via direction indicator enable */
    tBool m_bEnableDirectionPlausibilization;

    /*! direction derived from speed controller actuator value */
    tBool m_bEnableSpeedControllerDirection;

    /*! deadband for speed controll direction. Values within the deadband (around 0) will not trigger an update of the direction*/
    tFloat32 m_f32SpeedControllerDeadband;

    /*! first sample was received from left wheel */
    tBool m_bfirstSampleReceivedLeftWheel;

    /*! first sample was received from right wheel */
    tBool m_bfirstSampleReceivedRightWheel;

    /*! last direction */
    tInt8 m_i8olddirection;

    /*! vector with last directions for filtering */
    std::vector<tInt8> m_vi8olddirection;

};




//*************************************************************************************************
/*! @} */ // end of group
#endif // _RPMFILTER_H_ 
